#!/usr/bin/env ruby
sleep 2               #wait 2 seconds
$my_SSID = 'ninja' #set global variable to SSID of your home network

result = IO::popen('airport -I').read
`scselect auto` unless result.include?($my_SSID) # default profile 'auto'
`scselect Home` if result.include?($my_SSID) # select preferred network
